@startuml

title Angular Basic Concepts

node "github://angular/angular" {
	package "packages" {
		package "core" {
			file "src/metadata/directives.ts" as directives.ts
		}
	}
}

package "Angular Framework" {

    package "Directives" as "pgk_directives" {
		[Directive]

		[Component] -up-> [Directive]: is a

    	package "Structural Directives" {
    		note as SDN
    		Structural Directives
    		---
    		- are indicated with `*`
    		- modify the DOM node they
    		are attached to
    		end note
        	[`*ngFor`]
        }
    }

    directives.ts -down-> pgk_directives


	' Templates

	package "Templates" as AT {
    	component TypeScript
    	component HTML
    }

    'Ivy Compiler

    package "Ivy" {
    	note as IvyN
    	Ivy
    	---
    	Compilation + Rendering pipeline
    	for Angular 9+
    	end note

        component Runtime
        component Compiler {
        	component AOT [
            	AOT
            	---
            	Ahead Of Time compilation
            ]
        }

        ' Component Definition generation
        Component --> Compiler
        component "Component Definition" as ComponentDef
        Compiler --> ComponentDef
    }

    ' Workspace

    component Workspace
}



@enduml
