@startuml

title Angular Basic Concepts

left to right direction

node "github://angular/angular" as GH_REPO {
	[core/src/metadata/directives.ts] <<TypeScript file>> as SRC_DIR
}

component Directives
component Templates
component Ivy [
	Ivy
	---
	Compilation + Rendering pipeline
]
component Workspace


Directives --> SRC_DIR: defined in

@enduml
