@startuml

title Angular Application components

node "Git Repo" {
	component Workspace {
	    [angular.json] <<Workspace Configuration>>
    	[Application1] <<Angular App>>
    	component Application2 <<Angular App>> {
'			left to right direction
			[ComponentTemplate.html] <<Angular Template>> as CT
			[CT] - [View1]
    	}

    	angular.json --> Application1: manages
    	angular.json --> Application2: manages
    }
}


@enduml
