@startuml

title Angular Application components

component "Angular Template" as AT

node "Git Repo" {
	file angular.json
	component Workspace {
    	[Application1]
    	component Application2 {
    		[Component1] - [View1]
    	}
    }

    angular.json -down-> Workspace: manages

	package Templates {
		file property_binding.html {
                		note as C
                			"<a [title]="object.property1"></a>"
                		end note
            	}

		file interpolation.html {
			note as eiN
				<h3> {{object.property}} </a>
			end note
		}
	}

	Templates -up-> AT: examples

}


@enduml
