@startuml

title Angular Application

component Workspace {

	component App1 {
		component Component1 {
			[template.html] ..> [class.ts]: binds
			[class.ts] .> [styles.css]: loads
			[class.ts] .> [template.html]: loads
		}

		component Component2 {
			[EmbeddedComponent1] -- [EmbeddedComponent2]: communication
		}

		[Component3]

		Component1 ..> events
		events )-- Component2
	}

	[angular.json] --> App1: configures
	[angular.json] --> [App2]: configures

}

@enduml
